name = "arc2-hattenhauer-net"
compatibility_date = "2026-07-12"

routes = [
  { pattern = "arc2.hattenhauer.net/*", zone_name = "hattenhauer.net" }
]

[assets]
directory = "./assets"

[env.staging]
name = "arc2-hattenhauer-net-staging"
routes = [
  { pattern = "staging.arc2.hattenhauer.net/*", zone_name = "hattenhauer.net" }
]
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[env.staging.assets]
directory = "./assets"
